package com.example.homeworkplanner.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF5079D8)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFA7C8FF)
val onPrimaryContainerLight = Color(0xFF1E487C)
val secondaryLight = Color(0xFF3E6ECF)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF8AAFFF)
val onSecondaryContainerLight = Color(0xFF1E427B)
val tertiaryLight = Color(0xFF3356C2)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF8EA9FF)
val onTertiaryContainerLight = Color(0xFF001F48)
val errorLight = Color(0xFF6484FF)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFB6D3FF)
val onErrorContainerLight = Color(0xFF3D5A8A)
val backgroundLight = Color(0xFFD7E9FF)
val onBackgroundLight = Color(0xFF1E2F53)
val surfaceLight = Color(0xFFD7E9FF)
val onSurfaceLight = Color(0xFF1E2F53)
val surfaceVariantLight = Color(0xFFC2D8FF)
val onSurfaceVariantLight = Color(0xFF4A6080)
val outlineLight = Color(0xFF6E91FF)
val outlineVariantLight = Color(0xFFBEDCFF)
val scrimLight = Color(0xFFFFFFFF)
val inverseSurfaceLight = Color(0xFF2D3D66)
val inverseOnSurfaceLight = Color(0xFFF7F9FF)
val inversePrimaryLight = Color(0xFFA4BEFF)




val primaryDark = Color(0xFFDBC66E)
val onPrimaryDark = Color(0xFF3A3000)
val primaryContainerDark = Color(0xFF534600)
val onPrimaryContainerDark = Color(0xFFF8E287)
val secondaryDark = Color(0xFFD1C6A1)
val onSecondaryDark = Color(0xFF363016)
val secondaryContainerDark = Color(0xFF4E472A)
val onSecondaryContainerDark = Color(0xFFEEE2BC)
val tertiaryDark = Color(0xFFA9D0B3)
val onTertiaryDark = Color(0xFF143723)
val tertiaryContainerDark = Color(0xFF2C4E38)
val onTertiaryContainerDark = Color(0xFFC5ECCE)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF493F18)
val onBackgroundDark = Color(0xFFE8E2D4)
val surfaceDark = Color(0xFF41391A)
val onSurfaceDark = Color(0xFFE8E2D4)
val surfaceVariantDark = Color(0xFF4B4739)
val onSurfaceVariantDark = Color(0xFFCDC6B4)
val outlineDark = Color(0xFF969080)
val outlineVariantDark = Color(0xFF4B4739)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE8E2D4)
val inverseOnSurfaceDark = Color(0xFF333027)
val inversePrimaryDark = Color(0xFF6D5E0F)